"""Invoke OrcaSlicer headless CLI for slicing."""

from __future__ import annotations

import base64
import io
import os
import re
import subprocess
import tempfile
import zipfile
from pathlib import Path
from typing import Any

_REPO = Path("/home/user/projects/ORCA_BELT")
_RELEASE = _REPO / "build/src/Release/orca-slicer"
_DEBUG   = _REPO / "build/src/Debug/orca-slicer"


def get_binary() -> str:
    """Get the OrcaSlicer binary path.

    Prefers ORCA_SLICER_BIN env var, then Release build, then Debug build.
    Release binary is skipped if it's 0 bytes (failed link).
    """
    if env := os.environ.get("ORCA_SLICER_BIN"):
        return env
    if _RELEASE.exists() and _RELEASE.stat().st_size > 0:
        return str(_RELEASE)
    if _DEBUG.exists() and _DEBUG.stat().st_size > 0:
        return str(_DEBUG)
    return str(_RELEASE)  # will fail with a clear error


def _inject_thumbnails(gcode_path: str, source_3mf: str) -> bool:
    """
    Inject PNG thumbnails from source_3mf into the gcode file.

    OrcaSlicer CLI cannot render 3D thumbnails without OpenGL context.
    The source 3MF already contains plate PNG thumbnails generated by the GUI.
    We inject them in the standard gcode thumbnail format that Moonraker/Fluidd parse.

    Format (per thumbnail):
        ; thumbnail begin WxH SIZE_BYTES
        ; BASE64_CHUNK (76 chars/line)
        ; thumbnail end

    Returns True if at least one thumbnail was injected.
    """
    try:
        with zipfile.ZipFile(source_3mf) as z:
            names = z.namelist()
            # Prefer plate_1.png (larger) for 300x300 slot, plate_1_small for 48x48
            thumbnails = {}
            for candidate, size_label in [
                ("Metadata/plate_1_small.png", "48x48"),
                ("Metadata/plate_1.png", "300x300"),
            ]:
                if candidate in names:
                    raw = z.read(candidate)
                    thumbnails[size_label] = raw
    except Exception:
        return False

    if not thumbnails:
        return False

    # Build thumbnail blocks
    blocks = []
    for size_label, raw in thumbnails.items():
        b64 = base64.b64encode(raw).decode("ascii")
        lines = [f"; thumbnail begin {size_label} {len(raw)}"]
        for i in range(0, len(b64), 76):
            lines.append(f"; {b64[i:i+76]}")
        lines.append("; thumbnail end")
        blocks.append("\n".join(lines))

    inject_text = "\n".join(blocks) + "\n"

    # Inject after ; HEADER_BLOCK_END (or at top if not found)
    with open(gcode_path, "r", errors="replace") as f:
        content = f.read()

    marker = "; HEADER_BLOCK_END"
    if marker in content:
        content = content.replace(marker, marker + "\n" + inject_text, 1)
    else:
        content = inject_text + content

    with open(gcode_path, "w") as f:
        f.write(content)

    return True


def _parse_layer_count(combined_output: str) -> int | None:
    """Extract final layer count from ORCA_BELT debug log lines."""
    # "ORCA_BELT slice_volumes: after top-removal: N layers remain"
    m = re.search(r"ORCA_BELT slice_volumes: after top-removal: (\d+) layers", combined_output)
    if m:
        return int(m.group(1))
    return None


def _parse_gcode_layer_count(gcode_path: str) -> int | None:
    """Count layer change markers in a G-code file."""
    try:
        count = 0
        with open(gcode_path, "r", errors="replace") as f:
            for line in f:
                if line.startswith(";LAYER_CHANGE") or line.startswith("; layer"):
                    count += 1
        return count if count > 0 else None
    except OSError:
        return None


def slice_model(
    model_3mf: str | Path,
    output_dir: str | Path | None = None,
    load_settings: str | Path | None = None,
    timeout: int = 300,
) -> dict[str, Any]:
    """Slice a 3MF model using OrcaSlicer headless CLI.

    Args:
        model_3mf: Path to input .3mf file.
        output_dir: Directory for output G-code. Defaults to temp dir.
        load_settings: Optional JSON preset file to override settings.
        timeout: Max seconds to wait for slicing.

    Returns:
        Dict with keys: success, gcode_path, stdout, stderr, returncode, duration_s.
    """
    import time

    model_3mf = Path(model_3mf).resolve()
    if not model_3mf.exists():
        return {
            "success": False,
            "gcode_path": None,
            "error": f"Model file not found: {model_3mf}",
            "returncode": -1,
        }

    if output_dir is None:
        output_dir = Path(tempfile.mkdtemp(prefix="orca_slice_"))
    else:
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

    binary = get_binary()
    if not Path(binary).exists():
        return {
            "success": False,
            "gcode_path": None,
            "error": f"OrcaSlicer binary not found: {binary}",
            "returncode": -1,
        }

    # Use --debug 3 (info level) to capture ORCA_BELT layer-count log lines
    cmd = [binary, "--debug", "3", "--slice", "1", "--outputdir", str(output_dir), str(model_3mf)]

    if load_settings:
        load_settings = Path(load_settings).resolve()
        cmd.extend(["--load-settings", str(load_settings)])

    t0 = time.monotonic()
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
            env={**os.environ,
                 "DISPLAY": os.environ.get("DISPLAY", ":11"),
                 "LIBGL_ALWAYS_SOFTWARE": "1",
                 "MESA_GL_VERSION_OVERRIDE": "3.3",
                 "GALLIUM_DRIVER": "llvmpipe"},
        )
    except subprocess.TimeoutExpired:
        return {
            "success": False,
            "gcode_path": None,
            "error": f"Slicing timed out after {timeout}s",
            "returncode": -1,
            "duration_s": timeout,
        }

    duration = time.monotonic() - t0

    # Find output gcode (OrcaSlicer writes .gcode.tmp if it exits with error/warning)
    gcode_files = list(output_dir.glob("*.gcode")) or list(output_dir.glob("*.gcode.tmp"))
    gcode_path = str(gcode_files[0]) if gcode_files else None

    # Success = gcode was produced (OrcaSlicer exits non-zero even on warnings)
    success = gcode_path is not None

    # Extract layer count from ORCA_BELT debug output (stderr carries log lines)
    combined = result.stdout + result.stderr
    layer_count = _parse_layer_count(combined)
    if layer_count is None and gcode_path:
        layer_count = _parse_gcode_layer_count(gcode_path)

    # Inject thumbnails from source 3MF (CLI can't render OpenGL thumbnails)
    thumbnails_injected = False
    if success and gcode_path:
        thumbnails_injected = _inject_thumbnails(gcode_path, str(model_3mf))

    return {
        "success": success,
        "gcode_path": gcode_path,
        "layer_count": layer_count,
        "output_dir": str(output_dir),
        "binary": binary,
        "stdout": result.stdout,
        "stderr": result.stderr,
        "returncode": result.returncode,
        "duration_s": round(duration, 2),
        "thumbnails_injected": thumbnails_injected,
    }
