#!/usr/bin/env python3
"""
calib_temp_belt_v2 — Use OrcaBelt's own positioned 3MF + add wedge for bed adhesion.

User-specified design (2026-05-12):
  - The 3MF "Nozzle temperature test.3mf" generated by OrcaBelt already has the
    tower correctly tilted (build transform Rx(-45°)+translation) and positioned.
  - In world coords post-3MF-transforms: tower bbox Y∈[13.77,85.61], Z∈[0,71.84].
    Tower's tilted-bottom-edge goes from (Y=13.77, Z=7.06) to (Y=20.83, Z=0)
    at 45° slope (= same plane as belt layers).
  - Add a triangular-prism wedge in YZ that ties to this bottom edge:
      V1 (Y=0, Z=0)        ← far-front corner on belt, gives Z_gcode=0 start
      V2 (Y=20.83, Z=0)    ← on belt at tower's far-Y corner
      V3 (Y=13.77, Z=7.06) ← tower's tilted-bottom-front corner
    Wedge V2-V3 edge coincides with tower's tilted-bottom-edge → continuity.
  - Bake all into a new 3MF with identity transforms.
  - Slice with OrcaSlicer CLI Release binary.
  - M104 inject LAYER-BOUND: post-wedge Z_gcode range split into N=len(temps)
    equal stripes, M104 at each transition.

Dry-run by default — gcode + report; no upload.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import zipfile
from pathlib import Path

import numpy as np
import trimesh

REPO = Path(__file__).resolve().parents[1]
# Source 3MF generated by OrcaBelt GUI — has belt 45° tilt baked into item transform.
ORCABELT_3MF_DEFAULT = Path("/tmp/calib_temp_belt_orcabelt.3mf")
MACHINE = REPO / "resources/profiles/IdeaFormer/machine/IdeaFormer IR3 V2 0.4 nozzle.json"
PROCESS = REPO / "resources/profiles/IdeaFormer/process/0.20mm Standard @IdeaFormer IR3 V2.json"
FILAMENT = REPO / "resources/profiles/IdeaFormer/filament/Generic PLA @IdeaFormer IR3 V2.json"
ORCA = REPO / "build/src/Release/orca-slicer"
GATE = REPO / "validation/belt_gcode_gate.py"

sys.path.insert(0, str(REPO / "validation"))
from orca_profile_flatten import flatten_profile  # noqa: E402


def load_tower_world_coords(src_3mf: Path) -> trimesh.Trimesh:
    """Load 3MF with all transforms applied → mesh in world coords."""
    scene = trimesh.load(str(src_3mf))
    if hasattr(scene, "to_geometry"):
        mesh = scene.to_geometry()
    elif hasattr(scene, "dump"):
        mesh = scene.dump(concatenate=True)
    else:
        mesh = scene
    if not isinstance(mesh, trimesh.Trimesh):
        raise RuntimeError(f"failed to flatten scene → {type(mesh)}")
    return mesh


def build_wedge_world(tower: trimesh.Trimesh) -> trimesh.Trimesh:
    """
    Wedge in world coords, designed to bridge Z_gcode=0 → tower min Z_gcode.

    Tower's tilted-bottom-edge slope = -1 in YZ (45° down-right). The wedge
    has triangular cross-section in YZ extruded across X (matching tower X).
    """
    b = tower.bounds
    x_min, x_max = b[0, 0], b[1, 0]

    # Find tower's two min-Z_gcode corners (where Y+Z is minimum on the tilted
    # bottom edge). The 45° tilt means Z_gcode reaches its minimum on two
    # corners of the original tower's bottom face after the build rotation:
    yz_sum = tower.vertices[:, 1] + tower.vertices[:, 2]
    min_yz = yz_sum.min()
    eps = 1e-3
    bottom_edge_mask = (yz_sum - min_yz) < eps
    bottom_vertices = tower.vertices[bottom_edge_mask]
    # Find the two extreme corners of the bottom edge in YZ plane
    # (extreme in Z direction: min Z and max Z)
    z_vals = bottom_vertices[:, 2]
    v_low_z_idx = z_vals.argmin()
    v_high_z_idx = z_vals.argmax()
    # V2 = the corner with Z=0 (or min Z) of the tilted bottom edge
    # V3 = the corner with high Z (top of the tilted bottom edge)
    v2 = bottom_vertices[v_low_z_idx]
    v3 = bottom_vertices[v_high_z_idx]
    print(f"  Tower tilted-bottom-edge V2={v2.tolist()} V3={v3.tolist()}")
    print(f"  Tower Z_gcode range: [{yz_sum.min():.2f}, {yz_sum.max():.2f}]")

    # V1 at (Y=0, Z=0) — far-front corner on belt giving Z_gcode=0 start
    # Use V2's Y and V3's Z to anchor; V1's Y=0 means wedge extends Y down to 0
    V1 = np.array([0, 0, 0])  # X dummy; will use x_min, x_max for the prism
    V2_yz = np.array([0, v2[1], v2[2]])
    V3_yz = np.array([0, v3[1], v3[2]])

    # 3D vertices for triangular prism (extruded along X from x_min to x_max)
    verts = np.array([
        [x_min, V1[1], V1[2]],     # 0: V1_left
        [x_max, V1[1], V1[2]],     # 1: V1_right
        [x_min, V2_yz[1], V2_yz[2]],   # 2: V2_left
        [x_max, V2_yz[1], V2_yz[2]],   # 3: V2_right
        [x_min, V3_yz[1], V3_yz[2]],   # 4: V3_left
        [x_max, V3_yz[1], V3_yz[2]],   # 5: V3_right
    ])
    faces = np.array([
        # V1-V2-V3 triangle face at x=x_min (normal -X)
        [0, 4, 2],
        # V1-V2-V3 triangle face at x=x_max (normal +X)
        [1, 3, 5],
        # V1-V2 edge extruded → rectangle face (on belt, Z=0)
        [0, 2, 3], [0, 3, 1],
        # V2-V3 edge extruded → rectangle face (tilted bottom, ties to tower)
        [2, 4, 5], [2, 5, 3],
        # V1-V3 edge extruded → rectangle face (sloped front)
        [0, 1, 5], [0, 5, 4],
    ])
    wedge = trimesh.Trimesh(vertices=verts, faces=faces)
    wedge.fix_normals()
    if not wedge.is_watertight:
        print(f"  WARN: wedge not watertight after build")
    return wedge


def export_3mf(mesh: trimesh.Trimesh, out_3mf: Path, project_config: dict):
    """Write a 3MF with the mesh + embedded project_settings.config."""
    out_3mf.parent.mkdir(parents=True, exist_ok=True)
    mesh.export(str(out_3mf), file_type="3mf")

    cfg_lines = []
    for k, v in project_config.items():
        if isinstance(v, list):
            v = ";".join(str(x) for x in v)
        cfg_lines.append(f"{k} = {v}\n")
    cfg_text = "".join(cfg_lines)

    tmp_3mf = out_3mf.with_suffix(".tmp.3mf")
    with zipfile.ZipFile(out_3mf, "r") as zin, zipfile.ZipFile(
        tmp_3mf, "w", zipfile.ZIP_DEFLATED
    ) as zout:
        for item in zin.namelist():
            zout.writestr(item, zin.read(item))
        zout.writestr("Metadata/project_settings.config", cfg_text)
    tmp_3mf.replace(out_3mf)


def slice_cli(in_3mf: Path, out_dir: Path, temps: list[int]) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    flat_machine = flatten_profile(MACHINE)
    settings_arg = f"{flat_machine};{PROCESS}"

    flat_fil_path = flatten_profile(FILAMENT)
    fil_data = json.loads(flat_fil_path.read_text())
    fil_data["nozzle_temperature_initial_layer"] = [str(temps[0])]
    fil_data["nozzle_temperature"] = [str(temps[0])]
    flat_fil_path.write_text(json.dumps(fil_data, indent=2))

    cmd = [
        str(ORCA),
        "--slice", "1",
        "--load-settings", settings_arg,
        "--load-filaments", str(flat_fil_path),
        "--outputdir", str(out_dir),
        str(in_3mf),
    ]
    print(f"[slice] {' '.join(cmd)}")
    res = subprocess.run(cmd, capture_output=True, text=True, timeout=180)
    if res.returncode != 0:
        print(f"[slice] STDERR:\n{res.stderr[-2000:]}")
        raise RuntimeError(f"orca-slicer exit {res.returncode}")

    flat_machine.unlink(missing_ok=True)
    flat_fil_path.unlink(missing_ok=True)

    gcodes = sorted(out_dir.glob("*.gcode"))
    if not gcodes:
        raise RuntimeError(f"no gcode produced in {out_dir}")
    return gcodes[0]


def inject_m104(gcode_path: Path, boundaries: list[tuple[float, int]]) -> int:
    src = gcode_path.read_text().splitlines(keepends=True)
    out_lines = []
    cursor = 0
    z_pat = re.compile(r"^;Z[: ]\s*(-?\d+(?:\.\d+)?)")
    z_height_pat = re.compile(r"^;Z_HEIGHT:\s*(-?\d+(?:\.\d+)?)")
    layer_change = ";LAYER_CHANGE"
    in_layer_after_change = False
    n_injected = 0

    for line in src:
        out_lines.append(line)
        if line.startswith(layer_change):
            in_layer_after_change = True
            continue
        if in_layer_after_change:
            m = z_pat.match(line) or z_height_pat.match(line)
            if m:
                cur_z = float(m.group(1))
                inj = None
                while cursor < len(boundaries) and cur_z >= boundaries[cursor][0]:
                    z_thr, T = boundaries[cursor]
                    inj = (
                        f"M104 S{T} ; calib-stripe-{cursor + 2} "
                        f"(z_gcode>={z_thr:.2f}mm)\n"
                    )
                    cursor += 1
                if inj:
                    out_lines.append(inj)
                    n_injected += 1
                in_layer_after_change = False

    gcode_path.write_text("".join(out_lines))
    return n_injected


def gate(gcode_path: Path) -> tuple[int, str]:
    res = subprocess.run(
        ["python3", str(GATE), str(gcode_path)],
        capture_output=True, text=True, timeout=60,
    )
    return res.returncode, "\n".join(res.stdout.splitlines()[-30:])


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--source-3mf", type=Path, default=ORCABELT_3MF_DEFAULT)
    ap.add_argument("--temps", default="195,205,215,225,235")
    ap.add_argument("--out", type=Path, default=Path("/tmp/calib_temp_belt_v2"))
    args = ap.parse_args()

    temps = [int(t) for t in args.temps.split(",")]
    n_zones = len(temps)
    assert n_zones >= 2

    print(f"=== Belt Temperature Tower (v2 — OrcaBelt 3MF + wedge) ===")
    print(f"  Source 3MF   : {args.source_3mf}")
    print(f"  Temperatures : {temps} °C")
    print(f"  Output       : {args.out}")
    print()

    print("[1/6] Loading OrcaBelt 3MF + extracting tower in world coords...")
    tower = load_tower_world_coords(args.source_3mf)
    tb = tower.bounds
    print(f"  Tower bounds (world): X=[{tb[0,0]:.2f},{tb[1,0]:.2f}], "
          f"Y=[{tb[0,1]:.2f},{tb[1,1]:.2f}], Z=[{tb[0,2]:.2f},{tb[1,2]:.2f}]")

    print("[2/6] Building wedge to bridge Z_gcode=0 → tower bottom edge...")
    wedge = build_wedge_world(tower)
    wb = wedge.bounds
    print(f"  Wedge bounds: X=[{wb[0,0]:.2f},{wb[1,0]:.2f}], "
          f"Y=[{wb[0,1]:.2f},{wb[1,1]:.2f}], Z=[{wb[0,2]:.2f},{wb[1,2]:.2f}]")
    wedge_yz = wedge.vertices[:, 1] + wedge.vertices[:, 2]
    wedge_max_yz = float(wedge_yz.max())
    print(f"  Wedge Z_gcode range: [{wedge_yz.min():.2f}, {wedge_max_yz:.2f}]")

    print("[3/6] Combining tower + wedge, exporting 3MF...")
    combined = trimesh.util.concatenate([tower, wedge])
    cb = combined.bounds
    z_gcode_min = float((combined.vertices[:, 1] + combined.vertices[:, 2]).min())
    z_gcode_max = float((combined.vertices[:, 1] + combined.vertices[:, 2]).max())
    print(f"  Combined bounds: X=[{cb[0,0]:.2f},{cb[1,0]:.2f}], "
          f"Y=[{cb[0,1]:.2f},{cb[1,1]:.2f}], Z=[{cb[0,2]:.2f},{cb[1,2]:.2f}]")
    print(f"  Combined Z_gcode range: [{z_gcode_min:.2f}, {z_gcode_max:.2f}]")
    print(f"  Estimated layers: {(z_gcode_max-z_gcode_min)/0.283:.0f}")

    out_3mf = args.out / "calib_temp_belt_v2.3mf"
    project_cfg = {
        "enable_support": 0,
        "support_threshold_angle": 30,
        "belt_support_wedge_layers": 1,
        "nozzle_temperature_initial_layer": temps[0],
        "nozzle_temperature": temps[0],
        "hot_plate_temp": 75,
        "hot_plate_temp_initial_layer": 75,
        "brim_type": "outer_only",
        "brim_width": 0,
        "enable_prime_tower": 0,
    }
    export_3mf(combined, out_3mf, project_cfg)

    print(f"[4/6] Slicing via Orca CLI Release...")
    gcode = slice_cli(out_3mf, args.out, temps)
    print(f"  Sliced: {gcode.name} ({gcode.stat().st_size} bytes)")

    # M104 layer-bound: split post-wedge Z_gcode into n_zones equal stripes.
    # The actual gcode Z_gcode_min may differ from our computed value due to
    # Orca's auto keel-align (e.g. Z shift to enforce Z_min ≥ 2mm). Read
    # actual layer 1 Z from the gcode to anchor boundaries.
    actual_z_min = None
    for line in gcode.read_text().splitlines():
        m = re.match(r"^;Z[: ]\s*(-?\d+(?:\.\d+)?)", line)
        if m:
            actual_z_min = float(m.group(1))
            break
    if actual_z_min is None:
        print("  WARN: couldn't read actual Z_min from gcode")
        actual_z_min = z_gcode_min

    actual_wedge_end = actual_z_min + (wedge_max_yz - z_gcode_min)
    actual_z_max = actual_z_min + (z_gcode_max - z_gcode_min)
    post_wedge_range = actual_z_max - actual_wedge_end
    seg_width = post_wedge_range / n_zones
    boundaries = []
    for i in range(1, n_zones):
        z_thr = actual_wedge_end + i * seg_width
        boundaries.append((z_thr, temps[i]))

    print(f"[5/6] Injecting M104 at zone boundaries (layer-bound):")
    print(f"  Actual Z_gcode: [{actual_z_min:.2f}, {actual_z_max:.2f}]")
    print(f"  Wedge end at Z_gcode≈{actual_wedge_end:.2f}, stripe width={seg_width:.2f}")
    for z, t in boundaries:
        print(f"  Z_gcode ≥ {z:.2f}mm → M104 S{t}")
    n_inj = inject_m104(gcode, boundaries)
    print(f"  Injected {n_inj} M104 lines (expected {len(boundaries)})")

    print(f"[6/6] Running belt_gcode_gate...")
    rc, gate_tail = gate(gcode)
    label = {0: "PASS", 1: "FAIL", 2: "WARN"}.get(rc, f"rc={rc}")
    print(f"  Gate result: {label}")
    print(f"  {'─' * 50}")
    print(gate_tail)

    info = {
        "gcode": str(gcode),
        "combined_bounds": {
            "x": [cb[0, 0], cb[1, 0]],
            "y": [cb[0, 1], cb[1, 1]],
            "z": [cb[0, 2], cb[1, 2]],
        },
        "z_gcode_range": [z_gcode_min, z_gcode_max],
        "actual_z_gcode_range": [actual_z_min, actual_z_max],
        "wedge_max_yz_design": wedge_max_yz,
        "actual_wedge_end": actual_wedge_end,
        "n_zones": n_zones,
        "temps": temps,
        "m104_boundaries": [{"z_gcode_mm": z, "temp": t} for z, t in boundaries],
        "gate_exit_code": rc,
        "gate_label": label,
        "m104_injections_actual": n_inj,
    }
    (args.out / "calib_info.json").write_text(json.dumps(info, indent=2))
    print(f"\nFinal gcode: {gcode}")
    print(f"DRY-RUN COMPLETE. No upload performed.")
    return 0 if rc != 1 else 2


if __name__ == "__main__":
    sys.exit(main())
